# Generated by Django 2.1 on 2018-08-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20180808_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_q',
            name='q_id',
        ),
    ]
